services:
  - type: web
    name: finance-tracker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    # ... rest unchanged ...
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://finance_tracker_c8v6_user:hbjDOlUvjBc7fQHpUWXwXz3w7PXGl5Ea@dpg-cvdgsrt6l47c73946et0-a/finance_tracker_c8v6

databases:
  - name: finance-tracker-db
    databaseName: finance_tracker
    plan: free 