services:
  - type: web
    name: finance-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: finance-tracker-db
          property: connectionString

databases:
  - name: finance-tracker-db
    databaseName: finance_tracker
    plan: free 